🚧 WIP
neuralmagic/guidellm pull request #20
Opened 2024-07-25 14:47 UTC by parfeniukink

2024-07-26 11:04 UTC, parfeniukink commented
@markurtz waiting for real secrets we are going to use here.

2024-08-01 14:42 UTC, markurtz requested changes

2024-08-01 14:42 UTC, markurtz commented on .github/workflows/development.yml
> +      - name: Publish to Internal PyPI
Need to either pull from or add this functionality to https://github.com/neuralmagic/nm-actions/ to standardize. Will update in slack on the flows, have clarification on what needs to go in place for this now

2024-08-01 14:42 UTC, markurtz commented on .github/workflows/development.yml
> +      - name: Build a binary wheel & Inject build props
let's create an action for standardization and sharing for tox build pathways in https://github.com/neuralmagic/nm-actions/

2024-08-01 14:42 UTC, markurtz commented on .github/workflows/nightly.yml
> +      - name: Publish to Internal PyPI
Add/pull from https://github.com/neuralmagic/nm-actions/

2024-08-01 14:42 UTC, markurtz commented on .github/workflows/nightly.yml
> +      - name: Build a binary wheel & Inject build props
Add/pull from https://github.com/neuralmagic/nm-actions/

2024-08-01 14:42 UTC, markurtz commented on .github/workflows/nightly.yml
> +      - name: Publish to Public PyPI
Add/pull from https://github.com/neuralmagic/nm-actions/

2024-08-01 14:42 UTC, markurtz commented on .github/workflows/nightly.yml
> +    needs: [unit-tests, integration-tests, e2e-tests]
One note on this, we want to always push nightly to our internal pypi to enable easier internal QA. Only push external nightly if tests pass

2024-08-01 14:42 UTC, markurtz commented on .github/workflows/release.yml
> +      - name: Build a binary wheel & Inject build props
Add/pull from https://github.com/neuralmagic/nm-actions/

2024-08-01 14:42 UTC, markurtz commented on .github/workflows/release.yml
> +      - name: Publish to Internal PyPI
Add/pull from https://github.com/neuralmagic/nm-actions/

2024-08-01 14:42 UTC, markurtz commented on .github/workflows/release.yml
> +      - name: Build a binary wheel & Inject build props
Add/pull from https://github.com/neuralmagic/nm-actions/

2024-08-01 14:42 UTC, markurtz commented on .github/workflows/release.yml
> +      - name: Publish to Public PyPI
Add/p[ull from https://github.com/neuralmagic/nm-actions/

2025-04-21 15:01 UTC, closed without merging